import type { Occupancy } from './types.ts';

const createId = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

export const OCCUPANCY_DATA: Occupancy[] = [
  {
    id: 'residential',
    name: 'Residential',
    subOccupancies: [
      { id: createId('Plotted Detached/Individual Residential building'), name: 'Plotted Detached/Individual Residential building', sanctionFeeRate: 15, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
      { id: createId('Semi-detached'), name: 'Semi-detached', sanctionFeeRate: 15, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
      { id: createId('Row housing'), name: 'Row housing', sanctionFeeRate: 20, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
      { id: createId('Apartment Building'), name: 'Apartment Building', sanctionFeeRate: 50, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
      { id: createId('Housing Project'), name: 'Housing Project', sanctionFeeRate: 50, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
      { id: createId('work-cum-residential'), name: 'work-cum-residential', sanctionFeeRate: 30, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
      { id: createId('Studio Apartments'), name: 'Studio Apartments', sanctionFeeRate: 45, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
      { id: createId('Dharmasala'), name: 'Dharmasala', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
      { id: createId('Dormitory'), name: 'Dormitory', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('EWS'), name: 'EWS', sanctionFeeRate: 10, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
      { id: createId('Low Income Housing'), name: 'Low Income Housing', sanctionFeeRate: 10, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
      { id: createId('Medium Income Housing'), name: 'Medium Income Housing', sanctionFeeRate: 12, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
      { id: createId('Hostel'), name: 'Hostel', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('Shelter House'), name: 'Shelter House', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
      { id: createId('Staff Qaurter'), name: 'Staff Qaurter', sanctionFeeRate: 25, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
    ]
  },
  {
    id: 'commercial',
    name: 'Commercial',
    subOccupancies: [
        { id: createId('Hotel'), name: 'Hotel', sanctionFeeRate: 60, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('5 Star Hotel'), name: '5 Star Hotel', sanctionFeeRate: 80, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Motels'), name: 'Motels', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Services for households'), name: 'Services for households', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Shop Cum Residential'), name: 'Shop Cum Residential', sanctionFeeRate: 45, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
        { id: createId('Bank'), name: 'Bank', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Resorts'), name: 'Resorts', sanctionFeeRate: 65, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('lagoons and lagoon resort'), name: 'lagoons and lagoon resort', sanctionFeeRate: 65, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Amusement Building/Park and water sports'), name: 'Amusement Building/Park and water sports', sanctionFeeRate: 70, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('financial services and stock exchanges'), name: 'financial services and stock exchanges', sanctionFeeRate: 70, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Cold Storage and Ice Factory'), name: 'Cold Storage and Ice Factory', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Commercial and Business Offices/Complex'), name: 'Commercial and Business Offices/Complex', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Convenience and Neighborhood Shopping'), name: 'Convenience and Neighborhood Shopping', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Professional offices'), name: 'Professional offices', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Departmental store'), name: 'Departmental store', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Gas Godown'), name: 'Gas Godown', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Godowns'), name: 'Godowns', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Good Storage'), name: 'Good Storage', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Guest Houses'), name: 'Guest Houses', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Holiday Resort'), name: 'Holiday Resort', sanctionFeeRate: 65, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Boarding and lodging houses'), name: 'Boarding and lodging houses', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Petrol Pump (Only Filling Station)'), name: 'Petrol Pump (Only Filling Station)', sanctionFeeRate: 60, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Petrol Pump (Filling Station and Service station)'), name: 'Petrol Pump (Filling Station and Service station)', sanctionFeeRate: 70, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('CNG Mother Station'), name: 'CNG Mother Station', sanctionFeeRate: 70, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Restaurant'), name: 'Restaurant', sanctionFeeRate: 58, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('local(retail) shopping'), name: 'local(retail) shopping', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Shopping Center'), name: 'Shopping Center', sanctionFeeRate: 60, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Shopping Mall'), name: 'Shopping Mall', sanctionFeeRate: 65, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Showroom'), name: 'Showroom', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Wholesale Storage (Perishable)'), name: 'Wholesale Storage (Perishable)', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Wholesale Storage (Non Perishable)'), name: 'Wholesale Storage (Non Perishable)', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Storage/ Hangers/ Terminal Depot'), name: 'Storage/ Hangers/ Terminal Depot', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Supermarkets'), name: 'Supermarkets', sanctionFeeRate: 60, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Ware House'), name: 'Ware House', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Wholesale Market'), name: 'Wholesale Market', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('media centres'), name: 'media centres', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('food courts'), name: 'food courts', sanctionFeeRate: 58, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Weigh bridges'), name: 'Weigh bridges', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Mercentile'), name: 'Mercentile', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
    ]
  },
  {
    id: 'public-semi-public-institutional',
    name: 'Public-Semi Public/Institutional',
    subOccupancies: [
        { id: createId('Auditorium'), name: 'Auditorium', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Banquet Hall'), name: 'Banquet Hall', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Cinema'), name: 'Cinema', sanctionFeeRate: 55, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Club'), name: 'Club', sanctionFeeRate: 45, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('music pavilions'), name: 'music pavilions', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Community Hall'), name: 'Community Hall', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Orphanage'), name: 'Orphanage', sanctionFeeRate: 10, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Old Age Home'), name: 'Old Age Home', sanctionFeeRate: 10, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Science Centre/Museum'), name: 'Science Centre/Museum', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Confernce Hall'), name: 'Confernce Hall', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Convention Hall'), name: 'Convention Hall', sanctionFeeRate: 45, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('sculpture complex'), name: 'sculpture complex', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Cultural Complex'), name: 'Cultural Complex', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Exhibition Center'), name: 'Exhibition Center', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Gymnasia'), name: 'Gymnasia', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Marriage Hall/Kalyan Mandap'), name: 'Marriage Hall/Kalyan Mandap', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Multiplex'), name: 'Multiplex', sanctionFeeRate: 60, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Musuem'), name: 'Musuem', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Place of worship'), name: 'Place of worship', sanctionFeeRate: 5, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Public Libraries'), name: 'Public Libraries', sanctionFeeRate: 15, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Recreation Bldg'), name: 'Recreation Bldg', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Sports Complex'), name: 'Sports Complex', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Stadium'), name: 'Stadium', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Theatre'), name: 'Theatre', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Administrative Buildings'), name: 'Administrative Buildings', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Government offices'), name: 'Government offices', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Local and semi Government offices'), name: 'Local and semi Government offices', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Police/Army/Barack'), name: 'Police/Army/Barack', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Social and welfare centres'), name: 'Social and welfare centres', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Clinic'), name: 'Clinic', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Dispensary'), name: 'Dispensary', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Yoga Center'), name: 'Yoga Center', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Diagnostic Centre'), name: 'Diagnostic Centre', sanctionFeeRate: 45, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Govt-Semi Govt. Hospital'), name: 'Govt-Semi Govt. Hospital', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Registered Trust'), name: 'Registered Trust', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Health centre'), name: 'Health centre', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Hospital'), name: 'Hospital', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Lab'), name: 'Lab', sanctionFeeRate: 45, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Maternity Home'), name: 'Maternity Home', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Medical Building'), name: 'Medical Building', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Nursing Home'), name: 'Nursing Home', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Polyclinic'), name: 'Polyclinic', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Rehabilitaion Center'), name: 'Rehabilitaion Center', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Veterinary Hospital for pet animals and birds'), name: 'Veterinary Hospital for pet animals and birds', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Research and Training Institute'), name: 'Research and Training Institute', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Police Station'), name: 'Police Station', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Fire Station'), name: 'Fire Station', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Jail/Prison'), name: 'Jail/Prison', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Post Office'), name: 'Post Office', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
    ]
  },
  {
    id: 'public-utility',
    name: 'Public Utility',
    subOccupancies: [
        { id: createId('Bill Collection Center'), name: 'Bill Collection Center', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Broadcasting-Transmission Centre'), name: 'Broadcasting-Transmission Centre', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Burial and cremation grounds'), name: 'Burial and cremation grounds', sanctionFeeRate: 5, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Public Distribution System Shop'), name: 'Public Distribution System Shop', sanctionFeeRate: 15, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Public Toilets in Public Area'), name: 'Public Toilets in Public Area', sanctionFeeRate: 10, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Public Utility Bldg'), name: 'Public Utility Bldg', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Sub-Station'), name: 'Sub-Station', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Telecommunication'), name: 'Telecommunication', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('water pumping stations'), name: 'water pumping stations', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('service and storage yards'), name: 'service and storage yards', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('electrical distribution depots'), name: 'electrical distribution depots', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
    ]
  },
  {
    id: 'industrial-zone',
    name: 'Industrial Zone',
    subOccupancies: [
      { id: createId('Industrial Buildings (Factories, Workshops, etc.)'), name: 'Industrial Buildings (Factories, Workshops, etc.)', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('Non Polluting Industrial'), name: 'Non Polluting Industrial', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('IT, ITES Buildings'), name: 'IT, ITES Buildings', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('SEZ Industrial'), name: 'SEZ Industrial', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('Loading/Unloading Spaces'), name: 'Loading/Unloading Spaces', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('Flatted Factory'), name: 'Flatted Factory', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
      { id: createId('small factories and etc falls in industrial'), name: 'small factories and etc falls in industrial', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
    ]
  },
  {
    id: 'education',
    name: 'Education',
    subOccupancies: [
        { id: createId('Coaching Centre'), name: 'Coaching Centre', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Commercial Institute'), name: 'Commercial Institute', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('College'), name: 'College', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Computer Training Institute'), name: 'Computer Training Institute', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Nursery School'), name: 'Nursery School', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Primary School'), name: 'Primary School', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Hostel (Captive)'), name: 'Hostel (Captive)', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('High School'), name: 'High School', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Play School'), name: 'Play School', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('crèche'), name: 'crèche', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('School for Mentally Challenged.'), name: 'School for Mentally Challenged.', sanctionFeeRate: 15, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Art academy'), name: 'Art academy', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Technical College'), name: 'Technical College', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Sports training centers'), name: 'Sports training centers', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Training Institute'), name: 'Training Institute', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Veterinary Institute'), name: 'Veterinary Institute', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Medical College'), name: 'Medical College', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Research and Training Center'), name: 'Research and Training Center', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
    ]
  },
  {
    id: 'transportation',
    name: 'Transportation',
    subOccupancies: [
        { id: createId('Airport'), name: 'Airport', sanctionFeeRate: 50, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Auto Stand'), name: 'Auto Stand', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Metro Station'), name: 'Metro Station', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Bus Stand'), name: 'Bus Stand', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Bus Terminal'), name: 'Bus Terminal', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('ISBT'), name: 'ISBT', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Railway station'), name: 'Railway station', sanctionFeeRate: 40, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Taxi Stand'), name: 'Taxi Stand', sanctionFeeRate: 20, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Multi Level Car Parking'), name: 'Multi Level Car Parking', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Public Parking'), name: 'Public Parking', sanctionFeeRate: 25, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Toll Plaza'), name: 'Toll Plaza', sanctionFeeRate: 35, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
        { id: createId('Truck Terminal'), name: 'Truck Terminal', sanctionFeeRate: 30, requiresDwellingUnits: false, eligibleForSecurityDeposit: true },
    ]
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    subOccupancies: [
        { id: createId('Agriculture Farm'), name: 'Agriculture Farm', sanctionFeeRate: 5, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Agro Godown'), name: 'Agro Godown', sanctionFeeRate: 10, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Agro-Research Farm'), name: 'Agro-Research Farm', sanctionFeeRate: 10, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Farm House'), name: 'Farm House', sanctionFeeRate: 15, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
        { id: createId('Country Homes'), name: 'Country Homes', sanctionFeeRate: 15, requiresDwellingUnits: true, eligibleForSecurityDeposit: false },
        { id: createId('Nursery and green houses'), name: 'Nursery and green houses', sanctionFeeRate: 8, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Polutry, Diary and Swine/Goat/Horse'), name: 'Polutry, Diary and Swine/Goat/Horse', sanctionFeeRate: 12, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Horticulture'), name: 'Horticulture', sanctionFeeRate: 8, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
        { id: createId('Seri culture'), name: 'Seri culture', sanctionFeeRate: 8, requiresDwellingUnits: false, eligibleForSecurityDeposit: false },
    ]
  },
  {
    id: 'mixed-use',
    name: 'Mixed Use',
    subOccupancies: [
        { id: createId('Mixed Use Building'), name: 'Mixed Use Building', sanctionFeeRate: 45, requiresDwellingUnits: true, eligibleForSecurityDeposit: true },
    ]
  },
];

export const FEE_RATES = {
    LAND_DEVELOPMENT: 5, // per sqm of Plot Area
    CWWC: 207.96, // per sqm of BUA
    TEMP_SHED: 2000, // per shed
    TEMP_RCC: 6458.34, // per sqm
    SECURITY_DEPOSIT: 100, // per sqm of BUA
    EIDP_CWWC_PERCENTAGE_BEFORE_2018: 0.01, // 1% of CWWC for projects before 2018
    EIDP_CWWC_PERCENTAGE_2018_ONWARDS: 0.15, // 15% of CWWC for projects from 2018 onwards
};